name: flutter_widget_guide
description: A flutter appliction listing all the widgets covered in Flutter widget of the week playlist.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.11+12

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.14.0
  url_launcher: ^5.1.2
  http: ^0.12.0+1
  youtube_player_flutter: ^6.0.3+2
  transparent_image: ^1.0.0
  package_info: ^0.4.0+6
  firebase_core: ^0.4.2
  firebase_analytics: ^5.0.9
  firebase_remote_config: ^0.3.0
  webview_flutter: ^0.3.11+2
  shared_preferences: ^0.5.3+4
  firebase_messaging: ^6.0.9
  firebase_admob: ^0.9.0+10
  provider: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/images/expanded_info.svg
      - assets/images/medium_icon.svg
      - assets/images/dp.png
      - assets/images/github.png
      - assets/images/linkedin.png
      - assets/images/twitter.png
      - assets/images/slack_icon.svg

  fonts:
      - family: Ubuntu
        fonts:
          - asset: assets/fonts/Ubuntu-Regular.ttf
      - family: Crimson
        fonts:
          - asset: assets/fonts/CrimsonText-Regular.ttf

